name: CI

on:
    pull_request:
        branches: [ main ]

jobs:
    test-node:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '22.x'
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test

    test-deno:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                deno-version: v2.x
             - name: Run tests
                run: "deno task test"

    test-bun:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
                with: latest
              bun-version:
            - name: Install dependencies
              run: bun install
            - name: Run lint
              run: bun run test
